export const sample = [
  {
    roomId: 1,
    title: '타이틀1',
    lastMemo: '라스트메모',
    memoCount: 5,
    isFavorites: false,
    isCompleate: false,
    isPin: false,
    isMemoLook: false,
    status: 1,
    createdAt: 156160,
    updatedAt: 156160,
    lastUpdateOn: 156160,
  },
  {
    roomId: 2,
    title: '타이틀2',
    lastMemo: '라스트메모',
    memoCount: 5,
    isFavorites: false,
    isCompleate: false,
    isPin: false,
    isMemoLook: false,
    status: 1,
    createdAt: 156160,
    updatedAt: 156160,
    lastUpdateOn: 156160,
  },
  {
    roomId: 3,
    title: '타이틀3',
    lastMemo: '라스트메모',
    memoCount: 5,
    isFavorites: false,
    isCompleate: false,
    isPin: false,
    isMemoLook: false,
    status: 1,
    createdAt: 156160,
    updatedAt: 156160,
    lastUpdateOn: 156160,
  },
  {
    roomId: 4,
    title: '타이틀4',
    lastMemo: '라스트메모',
    memoCount: 5,
    isFavorites: false,
    isCompleate: false,
    isPin: false,
    isMemoLook: false,
    status: 1,
    createdAt: 156160,
    updatedAt: 156160,
    lastUpdateOn: 156160,
  },
  {
    roomId: 5,
    title: '타이틀5',
    lastMemo: '라스트메모',
    memoCount: 5,
    isFavorites: false,
    isCompleate: false,
    isPin: false,
    isMemoLook: false,
    status: 1,
    createdAt: 156160,
    updatedAt: 156160,
    lastUpdateOn: 156160,
  },
  {
    roomId: 6,
    title: '타이틀6',
    lastMemo: '라스트메모',
    memoCount: 5,
    isFavorites: false,
    isCompleate: false,
    isPin: false,
    isMemoLook: false,
    status: 1,
    createdAt: 156160,
    updatedAt: 156160,
    lastUpdateOn: 156160,
  },
  {
    roomId: 7,
    title: '타이틀7',
    lastMemo: '라스트메모',
    memoCount: 5,
    isFavorites: false,
    isCompleate: false,
    isPin: false,
    isMemoLook: false,
    status: 1,
    createdAt: 156160,
    updatedAt: 156160,
    lastUpdateOn: 156160,
  },
  {
    roomId: 8,
    title: '타이틀8',
    lastMemo: '라스트메모',
    memoCount: 5,
    isFavorites: false,
    isCompleate: false,
    isPin: false,
    isMemoLook: false,
    status: 1,
    createdAt: 156160,
    updatedAt: 156160,
    lastUpdateOn: 156160,
  },
  {
    roomId: 9,
    title: '타이틀9',
    lastMemo: '라스트메모',
    memoCount: 5,
    isFavorites: false,
    isCompleate: false,
    isPin: false,
    isMemoLook: false,
    status: 1,
    createdAt: 156160,
    updatedAt: 156160,
    lastUpdateOn: 156160,
  },
  {
    roomId: 10,
    title: '타이틀10',
    lastMemo: '라스트메모',
    memoCount: 5,
    isFavorites: false,
    isCompleate: false,
    isPin: false,
    isMemoLook: false,
    status: 1,
    createdAt: 156160,
    updatedAt: 156160,
    lastUpdateOn: 156160,
  },
  {
    roomId: 11,
    title: '타이틀11',
    lastMemo: '라스트메모',
    memoCount: 5,
    isFavorites: false,
    isCompleate: false,
    isPin: false,
    isMemoLook: false,
    status: 1,
    createdAt: 156160,
    updatedAt: 156160,
    lastUpdateOn: 156160,
  },
  {
    roomId: 12,
    title: '타이틀12',
    lastMemo: '라스트메모',
    memoCount: 5,
    isFavorites: false,
    isCompleate: false,
    isPin: false,
    isMemoLook: false,
    status: 1,
    createdAt: 156160,
    updatedAt: 156160,
    lastUpdateOn: 156160,
  },
  {
    roomId: 13,
    title: '타이틀13',
    lastMemo: '라스트메모',
    memoCount: 5,
    isFavorites: false,
    isCompleate: false,
    isPin: false,
    isMemoLook: false,
    status: 1,
    createdAt: 156160,
    updatedAt: 156160,
    lastUpdateOn: 156160,
  },
  {
    roomId: 14,
    title: '타이틀14',
    lastMemo: '라스트메모',
    memoCount: 5,
    isFavorites: false,
    isCompleate: false,
    isPin: false,
    isMemoLook: false,
    status: 1,
    createdAt: 156160,
    updatedAt: 156160,
    lastUpdateOn: 156160,
  },
  {
    roomId: 15,
    title: '타이틀15',
    lastMemo: '라스트메모',
    memoCount: 5,
    isFavorites: false,
    isCompleate: false,
    isPin: false,
    isMemoLook: false,
    status: 1,
    createdAt: 156160,
    updatedAt: 156160,
    lastUpdateOn: 156160,
  },
  {
    roomId: 16,
    title: '타이틀16',
    lastMemo: '라스트메모',
    memoCount: 5,
    isFavorites: false,
    isCompleate: false,
    isPin: false,
    isMemoLook: false,
    status: 1,
    createdAt: 156160,
    updatedAt: 156160,
    lastUpdateOn: 156160,
  },
  {
    roomId: 17,
    title: '타이틀17',
    lastMemo: '라스트메모',
    memoCount: 5,
    isFavorites: false,
    isCompleate: false,
    isPin: false,
    isMemoLook: false,
    status: 1,
    createdAt: 156160,
    updatedAt: 156160,
    lastUpdateOn: 156160,
  },
  {
    roomId: 18,
    title: '타이틀18',
    lastMemo: '라스트메모',
    memoCount: 5,
    isFavorites: false,
    isCompleate: false,
    isPin: false,
    isMemoLook: false,
    status: 1,
    createdAt: 156160,
    updatedAt: 156160,
    lastUpdateOn: 156160,
  },
  {
    roomId: 19,
    title: '타이틀19',
    lastMemo: '라스트메모',
    memoCount: 5,
    isFavorites: false,
    isCompleate: false,
    isPin: false,
    isMemoLook: false,
    status: 1,
    createdAt: 156160,
    updatedAt: 156160,
    lastUpdateOn: 156160,
  },
  {
    roomId: 20,
    title: '타이틀20',
    lastMemo: '라스트메모',
    memoCount: 5,
    isFavorites: false,
    isCompleate: false,
    isPin: false,
    isMemoLook: false,
    status: 1,
    createdAt: 156160,
    updatedAt: 156160,
    lastUpdateOn: 156160,
  },
];
